const Stack = require('./Stack');
const Queue = require('./Queue');
const LinkedList = require('./LinkedList');
const DoubleLinkedList = require('./DoubleLinkedList');
const Set = require('./Set');
const Dictionary = require('./Dictionary');
const BST = require('./BinarySearchTree');
const Graph = require('./GraphAdjMatrix');
const Sort = require('./Sort');

// let G = new Graph();
// G.addVertices('A');
// G.addVertices('B');
// G.addVertices('C');
// G.addVertices('D');
// G.addVertices('E');
// G.addVertices('F');
// G.addEdge('A','B');
// G.addEdge('A','C');
// G.addEdge('B','C');
// G.addEdge('B','D');
// G.addEdge('D','E');
// G.addEdge('C','F');
// G.DFS();

let s = new Sort();
s.createTestArray(1000000);
let start = Date.now();
s.quickSort();
let end = Date.now();
//console.log(s.toString());
console.log('time : ' + (end - start));