const Stack = require('./Stack');
const Queue = require('./Queue');
const LinkedList = require('./LinkedList');
const DoubleLinkedList = require('./DoubleLinkedList');
const Set = require('./Set');
const Dictionary = require('./Dictionary');
const BST = require('./BinarySearchTree');
const Graph = require('./Graph');

let G = new Graph();
G.addVertices('A');
G.addVertices('B');
G.addVertices('C');
G.addVertices('D');
G.addVertices('E');
G.addVertices('F');
G.addEdge('A','B');
G.addEdge('A','C');
G.addEdge('B','C');
G.addEdge('B','D');
G.addEdge('D','E');
G.addEdge('C','F');
G.DFS();